### ISSUE TITLE
Running integration tests requires LB_CLIENT_DEV environment variable set

### ISSUE THREAD

**Issue by alechenninger** [paterczm/lightblue-metadata-manager#5]
It looks like the test is supposed to used embedded lightblue on localhost, but I think it is actually using whatever lightblue the user has configured in LB_CLIENT_DEV configuration.

I started working on a PR to inject a FileSystem to the cli so you could perform this test against an in memory filesystem like jimfs (https://github.com/google/jimfs)

**Comment by paterczm** [comment]
> It looks like the test is supposed to used embedded lightblue on localhost, but I think it is actually using whatever lightblue the user has configured in LB_CLIENT_DEV configuration.

Why do you think so? MetadataManagerIntegrationTest is passing a client pointing at embedded Lightblue to MetadataManagerCli's constructor.

Jims looks interesting though.

**Comment by alechenninger** [comment]
I think I found that it is using the test client and not the environment variable, but it is still checking for the environment variable anyway. It's been a little while since I looked. The symptom was I think I could not run tests because I did not have the environment variable defined.

**Comment by paterczm** [comment]
It is using the right client, but it's still requiring that env variable. Input validation error.

https://github.com/paterczm/lightblue-metadata-manager/pull/7
